<?php
function olmo_blog_options( $options = array() ){
	$options = array(
    array(
      'id'          => 'blog_content_show',
      'label'       => esc_html__( 'Show Blog Content', 'olmo' ),
      'desc'        => '',
      'std'         => 'on',
      'type'        => 'on-off',
      'section'     => 'blog_options',
      'rows'        => '',
      'post_type'   => '',
      'taxonomy'    => '',
      'min_max_step'=> '',
      'class'       => '',
      'condition'   => '',
      'operator'    => 'and'
    ),
	array(
        'id'          => 'blog_title',
        'label'       => esc_html__( 'Blog Header Title', 'olmo' ),
        'desc'        => esc_html__( 'Blog page header title', 'olmo' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'blog_subtitle',
        'label'       => esc_html__( 'Blog Header Sub-Title', 'olmo' ),
        'desc'        => esc_html__( 'Blog page header sub-title', 'olmo' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'blog_layout',
        'label'       => esc_html__( 'Blog layout', 'olmo' ),
        'desc'        => esc_html__( 'Blog layout for blog page', 'olmo' ),
        'std'         => 'rs',
        'type'        => 'radio-image',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'full',
            'label'       => esc_html__( 'Full width', 'olmo' ),
            'src'         => OT_URL . '/assets/images/layout/full-width.png'
          ),
          array(
            'value'       => 'ls',
            'label'       => esc_html__( 'Left sidebar', 'olmo' ),
            'src'         => OT_URL . '/assets/images/layout/left-sidebar.png'
          ),
          array(
            'value'       => 'rs',
            'label'       => esc_html__( 'Right sidebar', 'olmo' ),
            'src'         => OT_URL . '/assets/images/layout/right-sidebar.png'
          )
        )
      ),
      array(
        'id'          => 'blog_sidebar',
        'label'       => esc_html__( 'Blog Sidebar', 'olmo' ),
        'desc'        => esc_html__( 'Select your blog sidebar', 'olmo' ),
        'std'         => 'sidebar-1',
        'type'        => 'sidebar-select',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'blog_layout:not(full)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'blog_single_title',
        'label'       => esc_html__( 'Blog Single Header Title', 'olmo' ),
        'desc'        => esc_html__( 'Blog single header title', 'olmo' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'blog_single_subtitle',
        'label'       => esc_html__( 'Blog Single Header Sub-Title', 'olmo' ),
        'desc'        => esc_html__( 'Blog single header sub-title', 'olmo' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'blog_header_banner_type',
        'label'       => esc_html__( 'Header Banner Type', 'olmo' ),
        'desc'        => esc_html__( 'Select your header banner type', 'olmo' ),
        'std'         => 'blog_custom_image',
        'type'        => 'select',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',
        'choices'     => array( 
          array(
            'value'       => 'blog_bg_color',
            'label'       => esc_html__( 'Background Color', 'olmo' ),
          ),
		  array(
            'value'       => 'blog_custom_image',
            'label'       => esc_html__( 'Custom Image', 'olmo' ),
          )
        )
      ),
	  array(
        'id'          => 'blog_header_custom_color',
        'label'       => esc_html__('Select Color', 'olmo'),
        'desc'        => '',
        'std'         => '#2f353e',
        'type'        => 'colorpicker',
		'section'     => 'blog_options',
        'class'       => '',
        'choices'     => array(),
        'operator'    => 'and',
        'condition'   => 'blog_header_banner_type:is(blog_bg_color)',
      ),
	  array(
        'id'          => 'blog_default_banner_image',
        'label'       => esc_html__( 'Background Image', 'olmo' ),
        'desc'        => esc_html__( 'Background image', 'olmo' ),
        'std'         => OLMOTHEMEURI. 'images/banner.jpg',
        'type'        => 'upload',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'blog_header_banner_type:is(blog_custom_image)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sticky_post_text',
        'label'       => esc_html__( 'Sticky post text', 'olmo' ),
        'desc'        => esc_html__( 'Sticky post text', 'olmo' ),
        'std'         => 'Featured',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'excerpt_length',
        'label'       => esc_html__( 'Excerpt Length', 'olmo' ),
        'desc'        => esc_html__( 'Excerpt Length', 'olmo' ),
        'std'         => '10',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'show_social_sharing_icons',
        'label'       => esc_html__( 'Display Social Sharing Icons', 'olmo' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'enable_post_thumb',
        'label'       => esc_html__( 'Post thumb in Single Post', 'olmo' ),
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'show_next_previous_single',
        'label'       => esc_html__( 'Display Next/Previous Posts in Single Post', 'olmo' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'show_text_in_blog',
        'label'       => esc_html__( 'Display "Latest Article" text in Blog', 'olmo' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_heading_text',
        'label'       => esc_html__( 'Blog Text Title', 'olmo' ),
        'desc'        => esc_html__( 'Blog "latest article" text', 'olmo' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_text_in_blog:is(on)',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'blog_comment_show',
        'label'       => esc_html__( 'Show Blog Comment', 'olmo' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'blog_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
    );

	return apply_filters( 'olmo_blog_options', $options );
}  
?>