<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class Olmo_Custom_Icon_Pack extends Elementor\Base_Data_Control {

	public function get_type() {
		return 'icon';
	}

	public static function get_icons() {

		$icons = array(
            'cs-icon cs-placeholder' => 'cs-icon cs-placeholder',
            'cs-icon cs-map' => 'cs-icon cs-map',
            'cs-icon cs-dollar' => 'cs-icon cs-dollar',
            'cs-icon cs-chat' => 'cs-icon cs-chat',
            'cs-icon cs-user' => 'cs-icon cs-user',
            'cs-icon cs-analytics' => 'cs-icon cs-analytics',
            'cs-icon cs-analytics-1' => 'cs-icon cs-analytics-1',
            'cs-icon cs-analytics-2' => 'cs-icon cs-analytics-2',
            'cs-icon cs-analytics-3' => 'cs-icon cs-analytics-3',
            'cs-icon cs-analytics-4' => 'cs-icon cs-analytics-4',
            'cs-icon cs-analytics-5' => 'cs-icon cs-analytics-5',
            'cs-icon cs-chat-1' => 'cs-icon cs-chat-1',
            'cs-icon cs-chat-2' => 'cs-icon cs-chat-2',
            'cs-icon cs-chat-3' => 'cs-icon cs-chat-3',
            'cs-icon cs-chat-4' => 'cs-icon cs-chat-4',
            'cs-icon cs-credit-card' => 'cs-icon cs-credit-card',
            'cs-icon cs-credit-card-1' => 'cs-icon cs-credit-card-1',
            'cs-icon cs-voice-message' => 'cs-icon cs-voice-message',
            'cs-icon cs-rotation-lock' => 'cs-icon cs-rotation-lock',
            'cs-icon cs-ballot' => 'cs-icon cs-ballot',
            'cs-icon cs-email' => 'cs-icon cs-email',
            'cs-icon cs-email-1' => 'cs-icon cs-email-1',
            'cs-icon cs-wireframe' => 'cs-icon cs-wireframe',
            'cs-icon cs-wireframe-1' => 'cs-icon cs-wireframe-1',
            'cs-icon cs-wireframe-2' => 'cs-icon cs-wireframe-2',
            'cs-icon cs-dashboard' => 'cs-icon cs-dashboard',
            'cs-icon cs-inside' => 'cs-icon cs-inside',
            'cs-icon cs-outside' => 'cs-icon cs-outside',
            'cs-icon cs-menu' => 'cs-icon cs-menu',
            'cs-icon cs-search' => 'cs-icon cs-search',
            'cs-icon cs-trash' => 'cs-icon cs-trash',
            'cs-icon cs-bulleye' => 'cs-icon cs-bulleye',
            'cs-icon cs-graph' => 'cs-icon cs-graph',
            'cs-icon cs-graph-1' => 'cs-icon cs-graph-1',
            'cs-icon cs-command' => 'cs-icon cs-command',
            'cs-icon cs-home' => 'cs-icon cs-home',
            'cs-icon cs-double-click' => 'cs-icon cs-double-click',
            'cs-icon cs-box' => 'cs-icon cs-box',
            'cs-icon cs-paperclip' => 'cs-icon cs-paperclip',
            'cs-icon cs-font' => 'cs-icon cs-font',
            'cs-icon cs-search-1' => 'cs-icon cs-search-1',
            'cs-icon cs-paint-roller' => 'cs-icon cs-paint-roller',
            'cs-icon cs-active' => 'cs-icon cs-active',
            'cs-icon cs-alarm' => 'cs-icon cs-alarm',
            'cs-icon cs-calendar' => 'cs-icon cs-calendar',
            'cs-icon cs-calendar-1' => 'cs-icon cs-calendar-1',
            'cs-icon cs-stopwatch' => 'cs-icon cs-stopwatch',
            'cs-icon cs-book' => 'cs-icon cs-book',
            'cs-icon cs-hashtag' => 'cs-icon cs-hashtag',
            'cs-icon cs-speech-bubble' => 'cs-icon cs-speech-bubble',
            'cs-icon cs-algorithm' => 'cs-icon cs-algorithm',
            'cs-icon cs-cloud-network' => 'cs-icon cs-cloud-network',
            'cs-icon cs-hierarchy' => 'cs-icon cs-hierarchy',
            'cs-icon cs-shift' => 'cs-icon cs-shift',
            'cs-icon cs-social-media' => 'cs-icon cs-social-media',
            'cs-icon cs-web-programming' => 'cs-icon cs-web-programming',
            'cs-icon cs-smartphone' => 'cs-icon cs-smartphone',
            'cs-icon cs-web-browser' => 'cs-icon cs-web-browser',
            'cs-icon cs-web-browser-1' => 'cs-icon cs-web-browser-1',
            'cs-icon cs-add' => 'cs-icon cs-add',
            'cs-icon cs-internet' => 'cs-icon cs-internet',
            'cs-icon cs-desktop' => 'cs-icon cs-desktop',
            'cs-icon cs-web-programming-1' => 'cs-icon cs-web-programming-1',
            'cs-icon cs-web-search-engine' => 'cs-icon cs-web-search-engine',
            'cs-icon cs-line-graph' => 'cs-icon cs-line-graph',
            'cs-icon cs-line-graph-1' => 'cs-icon cs-line-graph-1',
            'cs-icon cs-increase' => 'cs-icon cs-increase',
            'cs-icon cs-back-camera' => 'cs-icon cs-back-camera',
            'cs-icon cs-smartphone-1' => 'cs-icon cs-smartphone-1',
            'cs-icon cs-rotate' => 'cs-icon cs-rotate',
            'cs-icon cs-smartphone-2' => 'cs-icon cs-smartphone-2',
            'cs-icon cs-calculator' => 'cs-icon cs-calculator',
            'cs-icon cs-key' => 'cs-icon cs-key',
            'cs-icon cs-office-building' => 'cs-icon cs-office-building',
            'cs-icon cs-folder' => 'cs-icon cs-folder',
            'cs-icon cs-add-1' => 'cs-icon cs-add-1',
            'cs-icon cs-folder-1' => 'cs-icon cs-folder-1',
            'cs-icon cs-graphs' => 'cs-icon cs-graphs',
            'cs-icon cs-alarm-clock' => 'cs-icon cs-alarm-clock',
            'cs-icon cs-hosting-servers' => 'cs-icon cs-hosting-servers',
            'cs-icon cs-upload' => 'cs-icon cs-upload',
            'cs-icon cs-download' => 'cs-icon cs-download',
            'cs-icon cs-copy' => 'cs-icon cs-copy',
            'cs-icon cs-image' => 'cs-icon cs-image',
            'cs-icon cs-wishlist' => 'cs-icon cs-wishlist',
            'cs-icon cs-menu-1' => 'cs-icon cs-menu-1',
            'cs-icon cs-phone-call' => 'cs-icon cs-phone-call',
            'cs-icon cs-reload' => 'cs-icon cs-reload',
            'cs-icon cs-chat-5' => 'cs-icon cs-chat-5',
            'cs-icon cs-reward' => 'cs-icon cs-reward',
            'cs-icon cs-command-line' => 'cs-icon cs-command-line',
            'cs-icon cs-arrow' => 'cs-icon cs-arrow',
            'cs-icon cs-add-2' => 'cs-icon cs-add-2',
            'cs-icon cs-book-1' => 'cs-icon cs-book-1',
            'cs-icon cs-love-message' => 'cs-icon cs-love-message',
            'cs-icon cs-new-window' => 'cs-icon cs-new-window',
            'cs-icon cs-video' => 'cs-icon cs-video',
            'cs-icon cs-share' => 'cs-icon cs-share',
            'cs-icon cs-folder-2' => 'cs-icon cs-folder-2',
            'cs-icon cs-stop' => 'cs-icon cs-stop',
            'cs-icon cs-coding' => 'cs-icon cs-coding',
            'cs-icon cs-add-3' => 'cs-icon cs-add-3',
            'cs-icon cs-diamond' => 'cs-icon cs-diamond',
            'cs-icon cs-repeat' => 'cs-icon cs-repeat',
            'cs-icon cs-cloud-computing' => 'cs-icon cs-cloud-computing',
            'cs-icon cs-share-1' => 'cs-icon cs-share-1',
            'cs-icon cs-translation' => 'cs-icon cs-translation',
            'cs-icon cs-airplay' => 'cs-icon cs-airplay',
            'cs-icon cs-click' => 'cs-icon cs-click',
            'cs-icon cs-resize' => 'cs-icon cs-resize',
            'cs-icon cs-slow-motion' => 'cs-icon cs-slow-motion',
            'cs-icon cs-shopping-bag' => 'cs-icon cs-shopping-bag',
            'cs-icon cs-filter' => 'cs-icon cs-filter',
            'cs-icon cs-list' => 'cs-icon cs-list',
            'cs-icon cs-equalizer' => 'cs-icon cs-equalizer',
            'cs-icon cs-send' => 'cs-icon cs-send',
            'cs-icon cs-voice-search' => 'cs-icon cs-voice-search',
            'cs-icon cs-server' => 'cs-icon cs-server',
            'cs-icon cs-server-1' => 'cs-icon cs-server-1',
            'cs-icon cs-color-palette' => 'cs-icon cs-color-palette',
            'cs-icon cs-web-design' => 'cs-icon cs-web-design',
            'cs-icon cs-target' => 'cs-icon cs-target',
            'cs-icon cs-speech-bubble-1' => 'cs-icon cs-speech-bubble-1',
            'cs-icon cs-settings' => 'cs-icon cs-settings',
            'cs-icon cs-worldwide' => 'cs-icon cs-worldwide',
            'cs-icon cs-shuttle' => 'cs-icon cs-shuttle',
            'cs-icon cs-shield' => 'cs-icon cs-shield',
            'cs-icon cs-wallet' => 'cs-icon cs-wallet',
            'cs-icon cs-cloud-computing-1' => 'cs-icon cs-cloud-computing-1',
            'cs-icon cs-help' => 'cs-icon cs-help',
            'cs-icon cs-seo' => 'cs-icon cs-seo',
            'cs-icon cs-click-1' => 'cs-icon cs-click-1',
            'cs-icon cs-flow-chart' => 'cs-icon cs-flow-chart',
            'cs-icon cs-pay-day' => 'cs-icon cs-pay-day',
            'cs-icon cs-priority' => 'cs-icon cs-priority',
            'cs-icon cs-speech-bubble-2' => 'cs-icon cs-speech-bubble-2',
            'cs-icon cs-speech-bubble-3' => 'cs-icon cs-speech-bubble-3',
            'cs-icon cs-list-1' => 'cs-icon cs-list-1',
            'cs-icon cs-faq' => 'cs-icon cs-faq',
            'cs-icon cs-settings-1' => 'cs-icon cs-settings-1',
            'cs-icon cs-binary-code' => 'cs-icon cs-binary-code',
            'cs-icon cs-album' => 'cs-icon cs-album',
            'cs-icon cs-price' => 'cs-icon cs-price',
            'cs-icon cs-tool' => 'cs-icon cs-tool',
            'cs-icon cs-time' => 'cs-icon cs-time',
            'cs-icon cs-shirt' => 'cs-icon cs-shirt',
            'cs-icon cs-puzzle' => 'cs-icon cs-puzzle',
            'cs-icon cs-deadline' => 'cs-icon cs-deadline',
            'cs-icon cs-tv' => 'cs-icon cs-tv',
            'cs-icon cs-negotiation' => 'cs-icon cs-negotiation',
            'cs-icon cs-layers' => 'cs-icon cs-layers',
            'cs-icon cs-idea' => 'cs-icon cs-idea',
            'cs-icon cs-record' => 'cs-icon cs-record',
            'cs-icon cs-radar' => 'cs-icon cs-radar',
            'cs-icon cs-gamepad' => 'cs-icon cs-gamepad',
            'cs-icon cs-signal' => 'cs-icon cs-signal',
            'cs-icon cs-speech-bubble-4' => 'cs-icon cs-speech-bubble-4',
            'cs-icon cs-server-2' => 'cs-icon cs-server-2',
            'cs-icon cs-shield-1' => 'cs-icon cs-shield-1',
            'cs-icon cs-firewall' => 'cs-icon cs-firewall',
            'cs-icon cs-process' => 'cs-icon cs-process',
            'cs-icon cs-24-hours' => 'cs-icon cs-24-hours',
            'cs-icon cs-fingerprint-scan' => 'cs-icon cs-fingerprint-scan',
            'cs-icon cs-folder-3' => 'cs-icon cs-folder-3',
            'cs-icon cs-folder-4' => 'cs-icon cs-folder-4',
            'cs-icon cs-tongue' => 'cs-icon cs-tongue',
            'cs-icon cs-secure' => 'cs-icon cs-secure',
            'cs-icon cs-increase-1' => 'cs-icon cs-increase-1',
            'cs-icon cs-gift' => 'cs-icon cs-gift',
            'cs-icon cs-browser' => 'cs-icon cs-browser',
            'cs-icon cs-shield-2' => 'cs-icon cs-shield-2',
            'cs-icon cs-keyboard' => 'cs-icon cs-keyboard',
            'cs-icon cs-filter-1' => 'cs-icon cs-filter-1',
            'cs-icon cs-click-3' => 'cs-icon cs-click-3',
            'cs-icon cs-download-1' => 'cs-icon cs-download-1',
            'cs-icon cs-file' => 'cs-icon cs-file',
            'cs-icon cs-pantone' => 'cs-icon cs-pantone',
            'cs-icon cs-avatar' => 'cs-icon cs-avatar',
            'cs-icon cs-left-quote' => 'cs-icon cs-left-quote',
            'cs-icon cs-heart' => 'cs-icon cs-heart',
            'cs-icon cs-half-star-shape' => 'cs-icon cs-half-star-shape',
            'cs-icon cs-star-half-empty' => 'cs-icon cs-star-half-empty',
            'cs-icon cs-star' => 'cs-icon cs-star',
            'cs-icon cs-star-1' => 'cs-icon cs-star-1',
            'cs-icon cs-heart-shape-outline' => 'cs-icon cs-heart-shape-outline',
            'cs-icon cs-reply-arrow' => 'cs-icon cs-reply-arrow',
            'cs-icon cs-play-button' => 'cs-icon cs-play-button',
            'cs-icon cs-play' => 'cs-icon cs-play',
            'cs-icon cs-right-arrow' => 'cs-icon cs-right-arrow',
            'cs-icon cs-magnifying-glass' => 'cs-icon cs-magnifying-glass',
            'cs-icon cs-plus-black-symbol' => 'cs-icon cs-plus-black-symbol',
            'cs-icon cs-minus-symbol' => 'cs-icon cs-minus-symbol',
            'cs-icon cs-left-arrow' => 'cs-icon cs-left-arrow',
            'cs-icon cs-right-arrow-1' => 'cs-icon cs-right-arrow-1',
            'cs-icon cs-down-arrow' => 'cs-icon cs-down-arrow',
            'cs-icon cs-instagram' => 'cs-icon cs-telegram',
            'cs-icon cs-whatsapp' => 'cs-icon cs-whatsapp',
            'cs-icon cs-linkedin' => 'cs-icon cs-linkedin',
            'cs-icon cs-viber' => 'cs-icon cs-spotify',
            'cs-icon cs-vk' => 'cs-icon cs-vk',
            'cs-icon cs-facebook' => 'cs-icon cs-facebook',
            'cs-icon cs-kakao-talk' => 'cs-icon cs-kakao-talk',
            'cs-icon cs-youtube' => 'cs-icon cs-youtube',
            'cs-icon cs-line' => 'cs-icon cs-line',
            'cs-icon cs-twitter' => 'cs-icon cs-twitter',
            'cs-icon cs-behance' => 'cs-icon cs-behance',
            'cs-icon cs-google-play' => 'cs-icon cs-google-play',
            'cs-icon cs-snapchat' => 'cs-icon cs-snapchat',
            'cs-icon cs-google-plus' => 'cs-icon cs-google-plus',
            'cs-icon cs-odnoklassniki' => 'cs-icon cs-odnoklassniki',
            'cs-icon cs-messenger' => 'cs-icon cs-messenger',
            'cs-icon cs-skype' => 'cs-icon cs-skype',
            'cs-icon cs-google-drive' => 'cs-icon cs-google-drive',
            'cs-icon cs-slack' => 'cs-icon cs-slack',
            'cs-icon cs-open-source' => 'cs-icon cs-open-source',
            'cs-icon cs-twitter-1' => 'cs-icon cs-twitter-1',
            'cs-icon cs-vimeo' => 'cs-icon cs-vimeo',
            'cs-icon cs-evernote' => 'cs-icon cs-evernote',
            'cs-icon cs-blogger' => 'cs-icon cs-blogger',
            'cs-icon cs-google-hangouts' => 'cs-icon cs-google-hangouts',
            'cs-icon cs-yelp' => 'cs-icon cs-yelp',
            'cs-icon cs-dropbox' => 'cs-icon cs-dropbox',
            'cs-icon cs-stack-overflow' => 'cs-icon cs-stack-overflow',
            'cs-icon cs-github' => 'cs-icon cs-github',
            'cs-icon cs-codepen' => 'cs-icon cs-codepen',
            'cs-icon cs-github-1' => 'cs-icon cs-github-1',
            'cs-icon cs-envato' => 'cs-icon cs-envato',
            'cs-icon cs-delicious' => 'cs-icon cs-delicious',
            'cs-icon cs-pinterest-round-logo' => 'cs-icon cs-pinterest-round-logo',
            'cs-icon cs-linkedin-logo' => 'cs-icon cs-linkedin-logo',
            'cs-icon cs-dribble-big-logo' => 'cs-icon cs-dribble-big-logo',
            'cs-icon cs-linux-platform' => 'cs-icon cs-linux-platform',
            'cs-icon cs-python' => 'cs-icon cs-python',
            'cs-icon cs-sketch' => 'cs-icon cs-sketch',
            'cs-icon cs-diamond-1' => 'cs-icon cs-diamond-1',
            'cs-icon cs-wordpress-logo' => 'cs-icon cs-wordpress-logo',
            'cs-icon cs-adobe' => 'cs-icon cs-adobe',
            'cs-icon cs-html-5' => 'cs-icon cs-html-5',
            'cs-icon cs-css-3' => 'cs-icon cs-css-3',
            'cs-icon cs-php' => 'cs-icon cs-php',
            'cs-icon cs-file-1' => 'cs-icon cs-file-1',
            'cs-icon cs-js' => 'cs-icon cs-js',
            'cs-icon cs-sql' => 'cs-icon cs-sql',
            'cs-icon cs-zip' => 'cs-icon cs-zip',
            'cs-icon cs-back' => 'cs-icon cs-back',
            'cs-icon cs-next' => 'cs-icon cs-next',
            'cs-icon cs-slack-1' => 'cs-icon cs-slack-1',
            'cs-icon cs-steam' => 'cs-icon cs-steam',
            'cs-icon cs-git' => 'cs-icon cs-git',
            'cs-icon cs-bookmark' => 'cs-icon cs-bookmark',
            'cs-icon cs-check' => 'cs-icon cs-check',
            'cs-icon cs-cancel' => 'cs-icon cs-cancel',
		);

		return $icons;
	}

	protected function get_default_settings() {
		return [
			'options' => self::get_icons(),
		];
	}

	public function content_template() {
		?>
		<div class="elementor-control-field">
			<label class="elementor-control-title">{{{ data.label }}}</label>
			<div class="elementor-control-input-wrapper">
				<select class="elementor-control-icon" data-setting="{{ data.name }}" data-placeholder="<?php esc_attr_e( 'Select Icon', 'olmo' ); ?>">
					<option value=""><?php esc_html_e( 'Select Icon', 'olmo' ); ?></option>
					<# _.each( data.options, function( option_title, option_value ) { #>
					<option value="{{ option_value }}">{{{ option_title }}}</option>
					<# } ); #>
				</select>
			</div>
		</div>
		<# if ( data.description ) { #>
		<div class="elementor-control-field-description">{{ data.description }}</div>
		<# } #>
		<?php
	}

}
